import {ArrowDownToLine,ArrowUpRight,GraduationCap,BriefcaseBusiness,Users,BookOpen,Wrench,Plane,MapPin} from 'lucide-react';
import Markdown from 'react-markdown';
import {DATA} from '@/data/resume';
import {SITE} from '@/data/site';
const projectLinks:Record<string,string>={'Gulfstream Aerospace':'gulfstream-aerospace','Humanoid Robot Club':'humanoid-robot-club','Purdue Space Program':'purdue-space-program','PlayAR':'playar'};
function Experience({item}:{item:(typeof DATA.extracurriculars)[number]}){return <div className="experience-row"><div className="experience-period mono">{item.start} – {item.end??SITE.resume.present}<span>{item.typeLabel}</span></div><div><h4>{item.org}</h4><p className="experience-role">{item.role}</p><p className="experience-location">{item.location}</p><div className="experience-copy"><Markdown>{item.description}</Markdown></div>{projectLinks[item.org]&&<a className="text-link" href={`#${projectLinks[item.org]}`}>{SITE.resume.projectLink}<ArrowUpRight size={15}/></a>}</div></div>}
function Heading({title,icon}:{title:string;icon:React.ReactNode}){return <div className="resume-section-heading">{icon}<h3>{title}</h3></div>}
export function FullResume(){const L=SITE.resume;return <section id="resume" className="resume-block" data-nav-section><header className="section-heading"><div><p className="eyebrow"><GraduationCap size={18}/>{L.eyebrow}</p><h2>{L.title}</h2><p className="section-description">{L.intro}</p></div><a href={DATA.resumeUrl} className="button-link" download="Gabriel-Duarte-Rengifo-Resume.pdf">{L.download}<ArrowDownToLine size={17}/></a></header>
<div className="resume-layout"><aside className="resume-aside"><img className="resume-portrait" src={SITE.identity.portrait} alt={SITE.identity.portraitAlt} width="76" height="76" loading="lazy"/><h3>{SITE.identity.name}</h3><p><MapPin size={14}/>{DATA.location}</p><nav aria-label={L.eyebrow}>{[['education',L.education],['experience',L.experience],['leadership',L.leadership],['coursework',L.coursework],['skills',L.skills],['aviation',L.aviation]].map(([id,label])=><a href={`#resume-${id}`} key={id}>{label}</a>)}</nav></aside><div className="resume-content">
<section id="resume-education" className="resume-section"><Heading title={L.education} icon={<GraduationCap size={21}/>}/>{DATA.education.map(e=><div className="education-entry" key={e.school}><div className="education-title"><h4>{e.school}</h4><span className="mono">{e.start} – {e.end}</span></div><p>{e.degree}</p><p className="education-note">{e.description}</p></div>)}</section>
<section id="resume-experience" className="resume-section"><Heading title={L.experience} icon={<BriefcaseBusiness size={20}/>}/>{DATA.extracurriculars.filter(i=>i.type!=='club').map(i=><Experience item={i} key={i.org}/>)}</section>
<section id="resume-leadership" className="resume-section"><Heading title={L.leadership} icon={<Users size={20}/>}/>{DATA.extracurriculars.filter(i=>i.org==='Humanoid Robot Club'||i.org==='Purdue Space Program').map(i=><Experience item={i} key={i.org}/>)}</section>
<section className="resume-section"><Heading title={L.earlier} icon={<Users size={20}/>}/>{DATA.extracurriculars.filter(i=>i.type==='club'&&i.org!=='Humanoid Robot Club'&&i.org!=='Purdue Space Program').map(i=><Experience item={i} key={i.org}/>)}</section>
<section id="resume-coursework" className="resume-section"><Heading title={L.coursework} icon={<BookOpen size={20}/>}/>{DATA.coursework.map(c=><div className="course-row" key={c.code}><span className="mono">{c.code}</span><div><h4>{c.title}</h4><p>{c.description}</p></div></div>)}</section>
<section id="resume-skills" className="resume-section"><Heading title={L.skills} icon={<Wrench size={20}/>}/>{DATA.skills.map(g=><div className="skill-row" key={g.category}><h4>{g.category}</h4><div className="work-tags">{g.items.map(t=><span key={t}>{t}</span>)}</div></div>)}</section>
<section id="resume-aviation" className="resume-section"><Heading title={L.aviation} icon={<Plane size={20}/>}/><div className="aviation-panel"><div><p className="eyebrow"><Plane size={17}/>{DATA.aviation.heading}</p><h4>{DATA.aviation.progress}</h4><p>{DATA.aviation.rating}</p></div><div className="flight-hours"><strong>{DATA.aviation.hours}</strong><span>{DATA.aviation.hoursLabel}</span></div></div><div className="language-row"><span>{DATA.aviation.languagesLabel}</span><p>{DATA.aviation.languages}</p></div><figure className="aviation-photo"><img src={DATA.aviation.image.src} width={DATA.aviation.image.width} height={DATA.aviation.image.height} alt={DATA.aviation.image.alt} loading="lazy"/><figcaption>{DATA.aviation.image.caption}</figcaption></figure></section>
</div></div></section>}
