import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowDownToLine, ArrowUpRight } from 'lucide-react';
import Markdown from 'react-markdown';
import { DATA } from '@/data/resume';
export const metadata: Metadata = { title: 'Résumé & background', description: 'Gabriel Duarte Rengifo’s extended résumé: engineering experience, leadership, education, technical skills, and private pilot certification.' };
const projectLinks: Record<string, string> = { 'Gulfstream Aerospace': 'gulfstream-aerospace', 'Humanoid Robot Club': 'humanoid-robot-club', 'Purdue Space Program': 'purdue-space-program', 'PlayAR': 'playar' };
function Experience({ item }: {
    item: (typeof DATA.extracurriculars)[number];
}) { return <section className="experience-row reveal"><div className="experience-period mono">{item.start} — {item.end ?? 'Present'}<span>{item.typeLabel}</span></div><div><h3>{item.org}</h3><p className="experience-role">{item.role}</p><p className="experience-location">{item.location}</p><div className="experience-copy"><Markdown>{item.description}</Markdown></div>{projectLinks[item.org] && <Link className="text-link" href={`/portfolio/${projectLinks[item.org]}/`}>Explore the project <ArrowUpRight size={15}/></Link>}</div></section>; }
export default function Resume() {
    return <main id="main" className="wrap resume-page"><header className="page-intro resume-intro"><p className="eyebrow">The extended résumé</p><h1>Engineering is what I study.<br /><span className="serif">Making is what I do.</span></h1><div className="intro-bottom"><p>I’m Gabriel, a Purdue aerospace engineering student and private pilot with experience across aviation, manufacturing, robotics, and product design.</p><a href={DATA.resumeUrl} className="button-link" download="Gabriel-Duarte-Rengifo-Resume.pdf">Download résumé <ArrowDownToLine size={17}/></a></div></header>
    <div className="resume-layout"><aside className="resume-aside"><div className="profile-small"><img src="/me.jpg" alt="Gabriel Duarte Rengifo" width="88" height="88"/><h2>Gabriel Duarte<br />Rengifo</h2><p>West Lafayette, Indiana</p></div><nav aria-label="Résumé sections">{[['education', 'Education'], ['experience', 'Engineering & work'], ['leadership', 'Technical leadership'], ['earlier', 'Earlier involvement'], ['coursework', 'Coursework'], ['skills', 'Skills & tools'], ['aviation', 'Aviation & languages']].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="resume-contact"><a href={`mailto:${DATA.contact.email}`}>Email ↗</a><a href={DATA.contact.social.LinkedIn.url} target="_blank" rel="noreferrer">LinkedIn ↗</a><span>U.S. citizen</span></div></aside>
    <div className="resume-content"><section id="education" className="resume-section"><div className="resume-section-heading"><span className="mono">01</span><h2>Education</h2></div>{DATA.education.map((e, i) => <div className="education-entry reveal" key={e.school}><div className="education-title"><h3>{e.school}</h3><span className="mono">{e.start} — {e.end}</span></div><p className="degree">{e.degree}</p>{i === 0 ? <><p className="education-note">GPA 3.44 / 4.0 · Expected graduation May 2029</p><p className="education-note">Humanoid Robot Club President · Purdue Space Program</p></> : <p className="education-note">{e.description}</p>}</div>)}</section>
    <section id="experience" className="resume-section"><div className="resume-section-heading"><span className="mono">02</span><h2>Engineering & work</h2></div>{DATA.extracurriculars.filter(i => i.type !== 'club').map(item => <Experience key={item.org} item={item}/>)}</section>
    <section id="leadership" className="resume-section"><div className="resume-section-heading"><span className="mono">03</span><h2>Technical leadership</h2></div>{DATA.extracurriculars.filter(i => i.org === 'Humanoid Robot Club' || i.org === 'Purdue Space Program').map(item => <Experience key={item.org} item={item}/>)}</section>
    <section id="earlier" className="resume-section"><div className="resume-section-heading"><span className="mono">04</span><h2>Earlier involvement</h2></div>{DATA.extracurriculars.filter(i => i.type === 'club' && i.org !== 'Humanoid Robot Club' && i.org !== 'Purdue Space Program').map(item => <Experience key={item.org} item={item}/>)}</section>
    <section id="coursework" className="resume-section"><div className="resume-section-heading"><span className="mono">05</span><h2>Selected coursework</h2></div>{DATA.coursework.map(c => <div className="course-row reveal" key={c.code}><span className="mono">{c.code}</span><div><h3>{c.title}</h3><p>{c.description}</p></div></div>)}</section>
    <section id="skills" className="resume-section"><div className="resume-section-heading"><span className="mono">06</span><h2>Skills & tools</h2></div>{DATA.skills.filter(g => g.category !== 'Certifications' && g.category !== 'Languages').map(g => <div className="skill-row" key={g.category}><h3>{g.category}</h3><div className="work-tags">{g.items.map(t => <span key={t}>{t}</span>)}</div></div>)}</section>
    <section id="aviation" className="resume-section"><div className="resume-section-heading"><span className="mono">07</span><h2>Beyond the desk</h2></div><div className="aviation-panel"><div><p className="eyebrow">FAA Part 61</p><h3>Private Pilot</h3><p>Airplane Single Engine Land</p></div><div><strong>55</strong><span>flight hours in current résumé</span></div></div><div className="language-row"><span>Languages</span><p>English · Spanish</p></div><div className="language-row"><span>Research presentations</span><p>Purdue fall and spring undergraduate research conferences — “Presentations with Distinction” at both.</p></div></section>
    </div></div></main>;
}
